<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
  <None Include="ticks.raw" CopyToOutputDirectory="PreserveNewest" />
  <None Include="ticks_sample.csv" CopyToOutputDirectory="PreserveNewest" />
  <None Include="ticks_result_sample.csv" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
</Project>
